/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Substitution;

import static Substitution.DBconnection.*;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;

/**
 *
 * @author Phanasorn Srisayam
 */
public class UserAdd extends javax.swing.JFrame {
    
    String filename = null;
    
    

    /**
     * Creates new form RegisterAcess
     */
    public UserAdd() {
        
        initComponents();
        DBconnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoleGroup = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        rdTeacher = new javax.swing.JRadioButton();
        rdStaff = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        PhotoPanel = new javax.swing.JPanel();
        btnImage = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();
        checkboxPhoto = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtPhonenum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Help = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1203, 734));
        setResizable(false);

        jLabel1.setText("Name");

        jLabel2.setText("Lastname");

        jLabel3.setText("Email");

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        jLabel6.setText("Repeat Password");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setText("Registration");

        RoleGroup.add(rdTeacher);
        rdTeacher.setText("Teacher");

        RoleGroup.add(rdStaff);
        rdStaff.setText("Staff");

        jLabel8.setText("Please insert your role*");

        PhotoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Upload Photo *Not Require"));

        btnImage.setText("Choose Image");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PhotoPanelLayout = new javax.swing.GroupLayout(PhotoPanel);
        PhotoPanel.setLayout(PhotoPanelLayout);
        PhotoPanelLayout.setHorizontalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhotoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImage)
                .addContainerGap())
            .addGroup(PhotoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        PhotoPanelLayout.setVerticalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhotoPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImage)
                .addContainerGap())
        );

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancle.setText("Cancle");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        checkboxPhoto.setText("Photo (OPTIONAL)");
        checkboxPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxPhotoActionPerformed(evt);
            }
        });

        jLabel10.setText("Phone number");

        jLabel11.setText("***Please select STAFF, Incase your name already there in a system.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(150, 150, 150)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail)
                                    .addComponent(txtLastname)
                                    .addComponent(txtname)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(rdTeacher)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdStaff))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtRePassword)
                                        .addGap(1, 1, 1))
                                    .addComponent(txtPassword)
                                    .addComponent(txtUsername)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtPhonenum)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkboxPhoto))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPhonenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rdStaff)
                    .addComponent(rdTeacher))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkboxPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btnCancle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        jMenu1.setText("File");

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK | java.awt.event.InputEvent.META_MASK));
        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        Help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK | java.awt.event.InputEvent.META_MASK));
        Help.setText("Help");
        jMenu2.add(Help);

        jMenuItem2.setText("Report Bug");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String Name = txtname.getText();
        String Lastname = txtLastname.getText();
        String Email = txtEmail.getText();
        String Username = txtUsername.getText();
        String Password = String.valueOf(txtPassword.getPassword());
        String RePassword = String.valueOf(txtRePassword.getPassword());
        String Phone = txtPhonenum.getText();
        
        TeacherAdd teacheradd = new TeacherAdd(); //Create OBJ: TeacherAdd form 
        MainForm mf = new MainForm(); //Create OBJ: Mainform
        
        
        if(Name.isEmpty() //Check TextBox Field 
                || Lastname.isEmpty() 
                || Email.isEmpty() 
                || Username.isEmpty()
                || Password.isEmpty()
                || RePassword.isEmpty()
                || Phone.isEmpty()
                && (rdTeacher.isSelected() || rdStaff.isSelected()
                && Password.equals(RePassword))){
            
             JOptionPane.showMessageDialog(null, "Please insert data in a text box", "Error", 2); //Message Warning to complete form 
            }
           
            else if (rdTeacher.isSelected() && checkboxPhoto.isSelected()) {
                
                try{
                    
                    
                    PreparedStatement ps = con.prepareStatement("INSERT INTO `user` (`firstname`, `lastname`, `email`, `username`, `password`, `phone_no`, `photo`) VALUES (?,?,?,?,?,?,?)");  
                    
                    ps.setString(1,Name);
                    ps.setString(2,Lastname);
                    ps.setString(3,Email);
                    ps.setString(4,Username);
                    ps.setString(5,Password);
                    ps.setString(6,Phone);
                    
                    File image = new File(filename);
                    FileInputStream fin=new FileInputStream(image);
                    
                    ps.setBinaryStream(7,fin,fin.available());  
                    int ii= ps.executeUpdate();  
                    System.out.println(ii + " records affected"); // LOG
                    JOptionPane.showMessageDialog(null, "Your registeration has been added. Please DO NOT share username and password with anyone", "Registration Complete", 2);
                    
                    this.dispose();
                    
                    
                    teacheradd.setVisible(true);
                    
                    con.close();
                    
                }catch(Exception e) {
                    e.printStackTrace();
                }
                
                
                
            }else if (rdStaff.isSelected() && checkboxPhoto.isSelected()){
                try{
                    
                    PreparedStatement ps = con.prepareStatement("INSERT INTO `user` (`firstname`, `lastname`, `email`, `username`, `password`, `phone_no`, `photo`) VALUES (?,?,?,?,?,?,?)");  
                    
                    ps.setString(1,Name);
                    ps.setString(2,Lastname);
                    ps.setString(3,Email);
                    ps.setString(4,Username);
                    ps.setString(5,Password);
                    ps.setString(6,Phone);
                    
                    File image = new File(filename);
                    FileInputStream fin=new FileInputStream(image);
                    
                    ps.setBinaryStream(7,fin,fin.available());  
                    int ii= ps.executeUpdate();  
                    System.out.println(ii + " records affected"); // LOG
                    JOptionPane.showMessageDialog(null, "Your registeration has been added. Please DO NOT share username and password with anyone", "Registration Complete", 2);
                    
                    con.close();
                    
                    mf.setVisible(true);
                    this.dispose();
                    
                }catch(Exception e) {
                    e.printStackTrace();
                }
            }
            else if (rdTeacher.isSelected()){
                try{
                    
                    PreparedStatement ps = con.prepareStatement("INSERT INTO `user` (`firstname`, `lastname`, `email`, `username`, `password`, `phone_no`) VALUES (?,?,?,?,?,?)");  
                    
                    ps.setString(1,Name);
                    ps.setString(2,Lastname);
                    ps.setString(3,Email);
                    ps.setString(4,Username);
                    ps.setString(5,Password);
                    ps.setString(6,Phone);
                    
                    int ii= ps.executeUpdate();  
                    System.out.println(ii + " records affected"); // LOG
                    JOptionPane.showMessageDialog(null, "Your registeration has been added. Please DO NOT share username and password with anyone", "Registration Complete", 2);
                    
                    this.dispose();
                    teacheradd.setVisible(true);
                    con.close();
                    
                }catch(Exception e) {
                    e.printStackTrace();
                }
            }
            else if (rdStaff.isSelected()){
                try{
                    
                    PreparedStatement ps = con.prepareStatement("INSERT INTO `user` (`firstname`, `lastname`, `email`, `username`, `password`, `phone_no`) VALUES (?,?,?,?,?,?)");  
                    
                    ps.setString(1,Name);
                    ps.setString(2,Lastname);
                    ps.setString(3,Email);
                    ps.setString(4,Username);
                    ps.setString(5,Password);
                    ps.setString(6,Phone);
                    
                    int ii= ps.executeUpdate();  
                    System.out.println(ii + " records affected"); // LOG
                    JOptionPane.showMessageDialog(null, "Your registeration has been added. Please DO NOT share username and password with anyone", "Registration Complete", 2);
                    
                    this.dispose();
                    
                    mf.setVisible(true);
                    
                    con.close();
                        
                }catch(Exception e) {
                    e.printStackTrace();
                }
            }
            
            
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblImage.getWidth(),lblImage.getHeight(), Image.SCALE_SMOOTH));
        lblImage.setIcon(imageIcon);
    }//GEN-LAST:event_btnImageActionPerformed

    private void checkboxPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxPhotoActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_MenuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Help;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JPanel PhotoPanel;
    private javax.swing.ButtonGroup RoleGroup;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox checkboxPhoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JRadioButton rdStaff;
    private javax.swing.JRadioButton rdTeacher;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhonenum;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
